# Misscall OTP
POST https://citcall.pub/v3/motp
Content-Type: application/json
Authorization: Apikey {YOUR_APIKEY}

{
	"msisdn": "6281234567890",
	"gateway": 0
}

#####
# SMS
POST https://citcall.pub/v3/sms
Content-Type: application/json
Authorization: Apikey {YOUR_APIKEY}
{	
	"msisdn": "6281234567890",
	"senderid": "citcall",
	"text": "Hello World!"
}

#####
# SMS OTP
POST https://citcall.pub/v3/smsotp
Content-Type: application/json
Authorization: Apikey {YOUR_APIKEY}
{	
	"msisdn": "6281234567890",
	"senderid": "citcall",
	"text": "Hello World!"
}